---

- name: Add webupd8team PPA repository
  apt_repository: 
    repo: 'ppa:webupd8team/java'
  when: ansible_os_family == 'Debian'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  when: ansible_os_family == 'Debian'


- name: Install Oracle java
  apt:
    name: oracle-java8-installer
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'



